apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: williambr2022/rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: 4f60e815c036aece1079bf395cb175f86d17755f
